### ISSUE TITLE
Numpy2Numpy需求极其庞大的显存

### ISSUE THREAD

**Issue by JasonLeon01** [modelscope/ClearerVoice-Studio#131]
在执行SS的时候报出：
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 422.62 GiB. GPU 1 has a total capacity of 23.69 GiB of which 4.56 GiB is free. Process 69171 has 12.03 GiB memory in use. Including non-PyTorch memory, this process has 7.08 GiB memory in use. Of the allocated memory 6.81 GiB is allocated by PyTorch, and 14.34 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

**Comment by JasonLeon01** [comment]
补充一下，似乎只有MossFormer2_SE_48K正常，其余的我试了FRCRN_SE_16K，也有报错
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 422.62 GiB. GPU 1 has a total capacity of 23.69 GiB of which 4.56 GiB is free. Process 69171 has 12.03 GiB memory in use. Including non-PyTorch memory, this process has 7.08 GiB memory in use. Of the allocated memory 6.81 GiB is allocated by PyTorch, and 14.34 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

**Comment by WangFeiji0928** [comment]
佬，这个问题解决了吗？

**Comment by WangFeiji0928** [comment]
看了一下代码，做一下显存回收就好了

**Comment by Dawsonqw** [comment]
> 看了一下代码，做一下显存回收就好了

请教一下这步需要修改源代码吗？我有个疑问，我输入的是1s语音音频转换为ndarray的数据，也会报 CUDA out of memory，也是因为同样的问题吗？看起来这个数据量并不大。

**Comment by Dawsonqw** [comment]
> > 看了一下代码，做一下显存回收就好了
> 
> 请教一下这步需要修改源代码吗？我有个疑问，我输入的是1s语音音频转换为ndarray的数据，也会报 CUDA out of memory，也是因为同样的问题吗？看起来这个数据量并不大。

已解决，需要手动更改源码。在需要做模型推理的地方加上 with torco.no_grad即可。
